//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba7c.WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAll", ReplyAction="http://tempuri.org/IService1/GetAllResponse")]
        string GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAll", ReplyAction="http://tempuri.org/IService1/GetAllResponse")]
        System.Threading.Tasks.Task<string> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDict", ReplyAction="http://tempuri.org/IService1/AddDictResponse")]
        string AddDict(string surname, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDict", ReplyAction="http://tempuri.org/IService1/AddDictResponse")]
        System.Threading.Tasks.Task<string> AddDictAsync(string surname, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdDict", ReplyAction="http://tempuri.org/IService1/UpdDictResponse")]
        string UpdDict(int id, string surname, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdDict", ReplyAction="http://tempuri.org/IService1/UpdDictResponse")]
        System.Threading.Tasks.Task<string> UpdDictAsync(int id, string surname, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelDict", ReplyAction="http://tempuri.org/IService1/DelDictResponse")]
        string DelDict(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelDict", ReplyAction="http://tempuri.org/IService1/DelDictResponse")]
        System.Threading.Tasks.Task<string> DelDictAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : laba7c.WS.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<laba7c.WS.IService1>, laba7c.WS.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<string> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public string AddDict(string surname, int number) {
            return base.Channel.AddDict(surname, number);
        }
        
        public System.Threading.Tasks.Task<string> AddDictAsync(string surname, int number) {
            return base.Channel.AddDictAsync(surname, number);
        }
        
        public string UpdDict(int id, string surname, int number) {
            return base.Channel.UpdDict(id, surname, number);
        }
        
        public System.Threading.Tasks.Task<string> UpdDictAsync(int id, string surname, int number) {
            return base.Channel.UpdDictAsync(id, surname, number);
        }
        
        public string DelDict(int id) {
            return base.Channel.DelDict(id);
        }
        
        public System.Threading.Tasks.Task<string> DelDictAsync(int id) {
            return base.Channel.DelDictAsync(id);
        }
    }
}
